In [1]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty array (2x2):\n", empty_array)

# 2. Initialize an all-ones array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All-ones array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value (e.g., 7)
fill_array = np.full((3, 3), 7)
print("\n3. Array filled with 7 (3x3):\n", fill_array)

# 4. Return a new array of zeros with the same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\n4. Zeros array with same shape as given array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\n5. Ones array with same shape as given array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Convert list to numpy array:\n", numpy_array)


1. Empty array (2x2):
 [[4.88057639e-310 0.00000000e+000]
 [1.22777155e-259 6.01347002e-154]]

2. All-ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros array with same shape as given array:
 [[0 0]
 [0 0]]

5. Ones array with same shape as given array:
 [[1 1]
 [1 1]]

6. Convert list to numpy array:
 [1 2 3 4]


In [2]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr_10_to_49 = np.arange(10, 50)
print("1. Array with values from 10 to 49:\n", arr_10_to_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix with values from 0 to 8:\n", matrix_0_to_8)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()
print("\n4. Random array of size 30:\n", random_array_30)
print("   Mean of the array:", mean_value)

# 5. Create a 10x10 array with random values and find the minimum and maximum
random_array_10x10 = np.random.random((10, 10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("\n5. 10x10 array with random values:\n", random_array_10x10)
print("   Minimum value:", min_value)
print("   Maximum value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero array with 5th element replaced by 1:\n", zero_array)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 matrix with checkerboard pattern:\n", checkerboard)

1. Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
 [0.8499118  0.63185376 0.46472385 0.74865406 0.29622946 0.33276583
 0.72678807 0.71125647 0.03026683 0.91280187 0.03249653 0.90085555
 0.67048212 0.11352224 0.65996411 0.23659654 0.42789312 0.32489445
 0.30384914 0.7583022  0.63850403 0.608624   0.15915632 0.04619041
 0.67916928 0.99335093 0.67806623 0.62436109 0.42645471 0.41675333]
   Mean of the array: 0.5134912785219394

5. 10x10 array with random values:
 [[0.85350122 0.94754642 0.53183444 0.64747427 0.48443877 0.9016407
  0.02163425 0.09107806 0.45630499 0.47884459]
 [0.90977417 0.14923232 0.2915208  0.56266332 0.15395556 0.69569377
  0.63295112 0.87844379 0.34619458 0.01889303]
 [0.83419858 0.56566563 0.80932199 

In [3]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_result = x + y
print("1. Addition of x and y:\n", add_result)

# 2. Subtract the two arrays
subtract_result = x - y
print("\n2. Subtraction of x and y:\n", subtract_result)

# 3. Multiply the array `x` by an integer (e.g., 3)
multiply_result = x * 3
print("\n3. Multiplication of x by 3:\n", multiply_result)

# 4. Find the square of each element in `x`
square_result = np.square(x)
print("\n4. Square of each element in x:\n", square_result)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)  # This is valid because `v` can act as a column vector
dot_xy = np.dot(x, y)
print("\n5. Dot products:")
print("   Dot product of v and w:", dot_vw)
print("   Dot product of x and v:\n", dot_xv)
print("   Dot product of x and y:\n", dot_xy)

# 6. Concatenate `x` and `y` along rows
concat_xy_row = np.concatenate((x, y), axis=0)
print("\n6. Concatenate x and y along rows:\n", concat_xy_row)

# Concatenate `v` and `w` along columns
concat_vw_column = np.column_stack((v, w))
print("\n6. Concatenate v and w along columns:\n", concat_vw_column)

# 7. Attempt to concatenate `x` and `v` (observe the error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7. Concatenate x and v:\n", concat_xv)
except ValueError as e:
    print("\n7. Concatenate x and v resulted in an error:")
    print(e)

1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5. Dot products:
   Dot product of v and w: 219
   Dot product of x and v:
 [29 77]
   Dot product of x and y:
 [[19 22]
 [50 58]]

6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

6. Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

7. Concatenate x and v resulted in an error:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [4]:
import numpy as np

# Define the matrices
A = np.array([[3, 4], [7, 8]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A with its inverse
result = np.dot(A, A_inv)

# Print the result
print("A * A^(-1) =\n", result)

A * A^(-1) =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [5]:
# Define the second matrix
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Print both results
print("AB =\n", AB)
print("BA =\n", BA)

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


In [6]:
# Compute (AB)^T
AB_T = np.transpose(AB)

# Compute B^T A^T
BT_AT = np.dot(np.transpose(B), np.transpose(A))

# Print both results
print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)

(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]


In [7]:
# Define the coefficient matrix A and the constant matrix B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

# Compute the solution using the inverse method
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

# Print the solution
print("Solution X =\n", X)

Solution X =
 [ 2.  1. -2.]


In [8]:
# Solve the linear equations using np.linalg.solve
X_solve = np.linalg.solve(A, B)

# Print the solution
print("Solution using np.linalg.solve X =\n", X_solve)

Solution using np.linalg.solve X =
 [ 2.  1. -2.]
